### ISSUE TITLE
Error: iron-session: Bad usage. Missing cookie name.

### ISSUE THREAD

**Issue by geromegrignon** [salahadin-dinsafa/realworld-front#1]
By following the instructions from the README file, I created the env file before running `npm run dev`.

I populated with these information:

```
COOKIE_NAME=donuts
COOKIE_PASSWORD=donuts
BASE_URL=https://api.realworld.io/api
NEXT_PUBLIC_RELATIVE_PATH=http://localhost:3000/api
```

But i get `Error: iron-session: Bad usage. Missing cookie name.` error.
How to fix it?

**Comment by salahadin-dinsafa** [comment]
COOKIE_PASSWORD length must be at least 32 character you can read more here 
[https://www.npmjs.com/package/iron-session]

**Comment by salahadin-dinsafa** [comment]
Dear cookies password length must be at least 32 character
